# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/cmake-3.13.0-rc1-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /opt/cmake-3.13.0-rc1-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alex/console-markdown

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alex/console-markdown

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/cmake-3.13.0-rc1-Linux-x86_64/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/cmake-3.13.0-rc1-Linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/console-markdown/CMakeFiles /home/alex/console-markdown/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/console-markdown/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named console-markdown

# Build rule for target.
console-markdown: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 console-markdown
.PHONY : console-markdown

# fast build rule for target.
console-markdown/fast:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/build
.PHONY : console-markdown/fast

#=============================================================================
# Target rules for targets named console-markdown-test

# Build rule for target.
console-markdown-test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 console-markdown-test
.PHONY : console-markdown-test

# fast build rule for target.
console-markdown-test/fast:
	$(MAKE) -f CMakeFiles/console-markdown-test.dir/build.make CMakeFiles/console-markdown-test.dir/build
.PHONY : console-markdown-test/fast

ColouredBuffer.o: ColouredBuffer.cpp.o

.PHONY : ColouredBuffer.o

# target to build an object file
ColouredBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/ColouredBuffer.cpp.o
.PHONY : ColouredBuffer.cpp.o

ColouredBuffer.i: ColouredBuffer.cpp.i

.PHONY : ColouredBuffer.i

# target to preprocess a source file
ColouredBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/ColouredBuffer.cpp.i
.PHONY : ColouredBuffer.cpp.i

ColouredBuffer.s: ColouredBuffer.cpp.s

.PHONY : ColouredBuffer.s

# target to generate assembly for a file
ColouredBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/ColouredBuffer.cpp.s
.PHONY : ColouredBuffer.cpp.s

StringUtils.o: StringUtils.cpp.o

.PHONY : StringUtils.o

# target to build an object file
StringUtils.cpp.o:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/StringUtils.cpp.o
.PHONY : StringUtils.cpp.o

StringUtils.i: StringUtils.cpp.i

.PHONY : StringUtils.i

# target to preprocess a source file
StringUtils.cpp.i:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/StringUtils.cpp.i
.PHONY : StringUtils.cpp.i

StringUtils.s: StringUtils.cpp.s

.PHONY : StringUtils.s

# target to generate assembly for a file
StringUtils.cpp.s:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/StringUtils.cpp.s
.PHONY : StringUtils.cpp.s

consolerenderer.o: consolerenderer.cpp.o

.PHONY : consolerenderer.o

# target to build an object file
consolerenderer.cpp.o:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/consolerenderer.cpp.o
.PHONY : consolerenderer.cpp.o

consolerenderer.i: consolerenderer.cpp.i

.PHONY : consolerenderer.i

# target to preprocess a source file
consolerenderer.cpp.i:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/consolerenderer.cpp.i
.PHONY : consolerenderer.cpp.i

consolerenderer.s: consolerenderer.cpp.s

.PHONY : consolerenderer.s

# target to generate assembly for a file
consolerenderer.cpp.s:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/consolerenderer.cpp.s
.PHONY : consolerenderer.cpp.s

libsoldout/array.o: libsoldout/array.c.o

.PHONY : libsoldout/array.o

# target to build an object file
libsoldout/array.c.o:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/libsoldout/array.c.o
.PHONY : libsoldout/array.c.o

libsoldout/array.i: libsoldout/array.c.i

.PHONY : libsoldout/array.i

# target to preprocess a source file
libsoldout/array.c.i:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/libsoldout/array.c.i
.PHONY : libsoldout/array.c.i

libsoldout/array.s: libsoldout/array.c.s

.PHONY : libsoldout/array.s

# target to generate assembly for a file
libsoldout/array.c.s:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/libsoldout/array.c.s
.PHONY : libsoldout/array.c.s

libsoldout/buffer.o: libsoldout/buffer.c.o

.PHONY : libsoldout/buffer.o

# target to build an object file
libsoldout/buffer.c.o:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/libsoldout/buffer.c.o
.PHONY : libsoldout/buffer.c.o

libsoldout/buffer.i: libsoldout/buffer.c.i

.PHONY : libsoldout/buffer.i

# target to preprocess a source file
libsoldout/buffer.c.i:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/libsoldout/buffer.c.i
.PHONY : libsoldout/buffer.c.i

libsoldout/buffer.s: libsoldout/buffer.c.s

.PHONY : libsoldout/buffer.s

# target to generate assembly for a file
libsoldout/buffer.c.s:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/libsoldout/buffer.c.s
.PHONY : libsoldout/buffer.c.s

libsoldout/markdown.o: libsoldout/markdown.c.o

.PHONY : libsoldout/markdown.o

# target to build an object file
libsoldout/markdown.c.o:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/libsoldout/markdown.c.o
.PHONY : libsoldout/markdown.c.o

libsoldout/markdown.i: libsoldout/markdown.c.i

.PHONY : libsoldout/markdown.i

# target to preprocess a source file
libsoldout/markdown.c.i:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/libsoldout/markdown.c.i
.PHONY : libsoldout/markdown.c.i

libsoldout/markdown.s: libsoldout/markdown.c.s

.PHONY : libsoldout/markdown.s

# target to generate assembly for a file
libsoldout/markdown.c.s:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/libsoldout/markdown.c.s
.PHONY : libsoldout/markdown.c.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/console-markdown-test.dir/build.make CMakeFiles/console-markdown-test.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/console-markdown-test.dir/build.make CMakeFiles/console-markdown-test.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/console-markdown-test.dir/build.make CMakeFiles/console-markdown-test.dir/main.cpp.s
.PHONY : main.cpp.s

parsers/cpp.o: parsers/cpp.cpp.o

.PHONY : parsers/cpp.o

# target to build an object file
parsers/cpp.cpp.o:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/parsers/cpp.cpp.o
.PHONY : parsers/cpp.cpp.o

parsers/cpp.i: parsers/cpp.cpp.i

.PHONY : parsers/cpp.i

# target to preprocess a source file
parsers/cpp.cpp.i:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/parsers/cpp.cpp.i
.PHONY : parsers/cpp.cpp.i

parsers/cpp.s: parsers/cpp.cpp.s

.PHONY : parsers/cpp.s

# target to generate assembly for a file
parsers/cpp.cpp.s:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/parsers/cpp.cpp.s
.PHONY : parsers/cpp.cpp.s

parsers/pawn.o: parsers/pawn.cpp.o

.PHONY : parsers/pawn.o

# target to build an object file
parsers/pawn.cpp.o:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/parsers/pawn.cpp.o
.PHONY : parsers/pawn.cpp.o

parsers/pawn.i: parsers/pawn.cpp.i

.PHONY : parsers/pawn.i

# target to preprocess a source file
parsers/pawn.cpp.i:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/parsers/pawn.cpp.i
.PHONY : parsers/pawn.cpp.i

parsers/pawn.s: parsers/pawn.cpp.s

.PHONY : parsers/pawn.s

# target to generate assembly for a file
parsers/pawn.cpp.s:
	$(MAKE) -f CMakeFiles/console-markdown.dir/build.make CMakeFiles/console-markdown.dir/parsers/pawn.cpp.s
.PHONY : parsers/pawn.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... console-markdown"
	@echo "... console-markdown-test"
	@echo "... ColouredBuffer.o"
	@echo "... ColouredBuffer.i"
	@echo "... ColouredBuffer.s"
	@echo "... StringUtils.o"
	@echo "... StringUtils.i"
	@echo "... StringUtils.s"
	@echo "... consolerenderer.o"
	@echo "... consolerenderer.i"
	@echo "... consolerenderer.s"
	@echo "... libsoldout/array.o"
	@echo "... libsoldout/array.i"
	@echo "... libsoldout/array.s"
	@echo "... libsoldout/buffer.o"
	@echo "... libsoldout/buffer.i"
	@echo "... libsoldout/buffer.s"
	@echo "... libsoldout/markdown.o"
	@echo "... libsoldout/markdown.i"
	@echo "... libsoldout/markdown.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... parsers/cpp.o"
	@echo "... parsers/cpp.i"
	@echo "... parsers/cpp.s"
	@echo "... parsers/pawn.o"
	@echo "... parsers/pawn.i"
	@echo "... parsers/pawn.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

